AllCops:
  TargetRubyVersion: 2.4
  Include:
    - lib/**/*.rb
    - spec/*.rb

  Exclude:
    - .gitignore
    - .rspec
    - .rubocop.yml
    - .travis.yml
    - Gemfile.lock
    - HISTORY.md
    - LICENSE.txt
    - README.md
    - script/**/*
    - vendor/**/*
    - gemfiles/**/*

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Layout/LineLength:
  Max: 100
