require: rubocop-jekyll

inherit_gem:
  rubocop-jekyll: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.5
  Include:
    - lib/**/*.rb

  Exclude:
    - .gitignore
    - .rspec
    - .rubocop.yml
    - .travis.yml
    - Gemfile.lock
    - HISTORY.md
    - LICENSE.txt
    - README.md
    - script/**/*
    - vendor/**/*
    - lib/cloudcannon-jekyll/safe-jsonify-filter.rb # TODO remove this and fix warnings

Naming/MemoizedInstanceVariableName:
  Exclude:
    - lib/cloudcannon-jekyll/page-without-a-file.rb
