require: rubocop-jekyll

inherit_gem:
  rubocop-jekyll: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.4
  Include:
    - lib/**/*.rb

  Exclude:
    - .gitignore
    - .rspec
    - .rubocop.yml
    - .travis.yml
    - Gemfile.lock
    - HISTORY.md
    - LICENSE.txt
    - README.md
    - script/**/*
    - vendor/**/*
    - gemfiles/**/*

Naming/MemoizedInstanceVariableName:
  Exclude:
    - lib/cloudcannon-jekyll/page-without-a-file.rb

Metrics/CyclomaticComplexity:
  Exclude:
    - lib/cloudcannon-jekyll/jsonify-filter.rb # TODO remove this and fix warnings
    - lib/cloudcannon-jekyll/readers/old-data-reader.rb # TODO remove this and fix warnings

Metrics/PerceivedComplexity:
  Exclude:
    - lib/cloudcannon-jekyll/jsonify-filter.rb # TODO remove this and fix warnings

Metrics/AbcSize:
  Exclude:
    - lib/cloudcannon-jekyll/jsonify-filter.rb # TODO remove this and fix warnings
