#!/bin/sh

set -ex

JEKYLL_VERSION=2.4.0 bundle update && $(dirname "$0")/test &&
JEKYLL_VERSION=3.0.0 bundle update && $(dirname "$0")/test &&
JEKYLL_VERSION=3.8.5 bundle update && $(dirname "$0")/test &&
JEKYLL_VERSION=4.2.1 bundle update && $(dirname "$0")/test

